server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:// :3306/ ?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username:
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update # disable DB schema creation from entity
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect # ??
    show-sql: true

flyway:
  baseline-on-migrate: true

sa-token:
  # jwt秘钥
  jwt-secret-key: asdasdasifhfwqfopwhfwailv345352ojnvsoivweot3425jsdafjk
  # token前缀
  token-prefix: Bearer
  #token名称 (同时也是cookie名称)
  token-name: Authorization
  #关闭读取Cookie中Token
  isReadCookie: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false